version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: html-to-text
    versions:
    - 6.0.0
    - 7.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: gulp-mocha
    versions:
    - 7.0.2
